#!/usr/bin/env python3
"""Autogenerate site/announcements/index.html from the announcement markdown files.

Scans site/announcements/*.md. Each announcement's first line is expected to be

    # <title> — <subtitle>

and its body may carry a `**Released:** <Month> <day>, <year>` marker, used for
newest-first ordering (files without a parseable date sort after dated ones,
by filename descending). The generated index preserves the site's look and is
a build artifact: CI (pages.yml) regenerates it at deploy time; it is
gitignored, never committed.

Usage: python3 scripts/generate-announcements-index.py [--root site/announcements]
"""
from __future__ import annotations

import argparse
import datetime as dt
import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

MONTHS = {m: i for i, m in enumerate(
    ["January", "February", "March", "April", "May", "June", "July",
     "August", "September", "October", "November", "December"], start=1)}
RELEASED_RE = re.compile(r"\*\*Released:\*\*\s+([A-Z][a-z]+)\s+(\d{1,2}),\s+(\d{4})")


def parse_announcement(path: Path) -> dict:
    """Extract title, subtitle, and release date from one announcement."""
    text = path.read_text(encoding="utf-8", errors="replace")
    title, subtitle = path.stem, ""
    for line in text.splitlines():
        if line.startswith("# "):
            heading = line[2:].strip()
            # split on em-dash variants: " — ", " -- ", " - "
            for sep in (" — ", " -- ", " - "):
                if sep in heading:
                    title, subtitle = (s.strip() for s in heading.split(sep, 1))
                    break
            else:
                title = heading
            break
    date = None
    m = RELEASED_RE.search(text)
    if m and m.group(1) in MONTHS:
        try:
            date = dt.date(int(m.group(3)), MONTHS[m.group(1)], int(m.group(2)))
        except ValueError:
            date = None
    return {"file": path.name, "title": title, "subtitle": subtitle, "date": date}


def generate_index(root: Path) -> Path:
    entries = [parse_announcement(p) for p in root.glob("*.md")]
    # Newest first: dated entries by date desc, then undated by filename desc.
    entries.sort(key=lambda e: (e["date"] is not None,
                                e["date"] or dt.date.min, e["file"]), reverse=True)
    items = []
    for e in entries:
        label = html.escape(e["title"])
        if e["subtitle"]:
            label += f" — {html.escape(e['subtitle'])}"
        when = f" <small>({e['date'].isoformat()})</small>" if e["date"] else ""
        items.append(f'    <li><a href="{e["file"]}">{label}</a>{when}</li>')
    index = root / "index.html"
    index.write_text(f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Announcements · synaptic-canvas</title>
  <style>
    body {{ font-family: -apple-system, system-ui, sans-serif; max-width: 52rem; margin: 3rem auto; padding: 0 1.5rem; line-height: 1.6; color: #1a1a2e; }}
    nav a {{ margin-right: 1rem; }}
    small {{ color: #666; }}
  </style>
</head>
<body>
  <nav><a href="../">&#8592; synaptic-canvas home</a></nav>
  <h1>Announcements</h1>
  <p>Press releases and release announcements for synaptic-canvas.
     Autogenerated by <code>scripts/generate-announcements-index.py</code> — do not edit.</p>
  <ul>
{chr(10).join(items)}
  </ul>
</body>
</html>
""", encoding="utf-8")
    return index


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="generate the announcements index")
    ap.add_argument("--root", type=Path, default=REPO_ROOT / "site" / "announcements")
    args = ap.parse_args(argv)
    if not args.root.is_dir():
        print(f"error: not a directory: {args.root}", file=sys.stderr)
        return 1
    index = generate_index(args.root)
    print(f"generated {index}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
